version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-luxfurn}
      MYSQL_USER: ${MYSQL_USER:-luxfurn_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-luxfurn_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PHP Web Application
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE:-luxfurn}
      DB_USER: ${MYSQL_USER:-luxfurn_user}
      DB_PASS: ${MYSQL_PASSWORD:-luxfurn_pass}
      RASA_URL: http://rasa:5005
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./Src:/app/Src

  # Rasa Chatbot
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
      - "5055:5055"
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE:-luxfurn}
      DB_USER: ${MYSQL_USER:-luxfurn_user}
      DB_PASS: ${MYSQL_PASSWORD:-luxfurn_pass}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: