FROM rasa/rasa:3.6.0

# Copy Rasa files
COPY . /app
WORKDIR /app

# Install dependencies
RUN pip install -r requirements-rasa.txt

# Train the model
RUN rasa train

# Expose ports
EXPOSE 5005 5055

# Start script
CMD ["sh", "-c", "rasa run actions & rasa run --enable-api --cors '*' --port 5005"]