[phases.setup]
nixPkgs = ["php", "php81Extensions.pdo_mysql", "php81Extensions.mysqli"]

[start]
cmd = "php -S 0.0.0.0:8080 -t ."

[phases.install]
cmd = "echo 'extension=pdo_mysql.so' > /etc/php/conf.d/pdo_mysql.ini && echo 'extension=mysqli.so' > /etc/php/conf.d/mysqli.ini"

[phases.build]
cmd = "cd web && composer install --no-dev --prefer-dist --optimize-autoloader"