[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "nginx", "php82Extensions.mbstring", "php82Extensions.curl"]

[phases.build]
cmds = ["mkdir -p /var/log/nginx", "mkdir -p /var/lib/nginx", "mkdir -p /tmp", "mkdir -p /var/run", "chmod +x start.sh"]

[phases.start]
cmd = "./start.sh"

[variables]
PORT = "8080"