[phases.setup]
nixPkgs = ["php", "phpExtensions.mysqli", "phpExtensions.pdo", "phpExtensions.pdo_mysql"]

[phases.build]
cmd = "cd web && composer install --no-dev --prefer-dist --optimize-autoloader"