[phases.setup]
nixPkgs = ["php", "phpExtensions.mysqli", "phpExtensions.pdo", "phpExtensions.pdo_mysql"]

[phases.build]
cmd = "composer install --no-dev --prefer-dist --optimize-autoloader"

[start]
cmd = "php -S 0.0.0.0:$PORT -t web"