# rasa/Dockerfile.rasa
FROM rasa/rasa:3.6.21-full

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN rasa train

EXPOSE 5005

CMD ["rasa", "run", "--enable-api", "--cors", "*", "--port", "5005"]
