[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.gd", "php82Extensions.zip"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php",
  "mv composer.phar /usr/local/bin/composer",
  "chmod +x /usr/local/bin/composer",
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = ["mkdir -p /tmp", "mkdir -p /var/log", "mkdir -p /var/run"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."