[phases.setup]
# Install PHP 8.2 and the MySQL drivers
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mysqli"]

[start]
# Use Railway's $PORT; serve your app from /app (Railway mounts your repo there)
# Explicitly load php.ini from the /app directory
cmd = "ls -l /opt/php/lib/php/extensions && php -i && php -S 0.0.0.0:${PORT} -t /app -c /app/php.ini"

[start]
# Use Railway's $PORT; serve your app from /app (Railway mounts your repo there)
# Explicitly load php.ini from the /app directory
cmd = "ls -l /opt/php/lib/php/extensions && php -S 0.0.0.0:${PORT} -t /app -c /app/php.ini"
